name: LCCUtilities
main: me.tick.lccutilities.LCCUtils
version: "${version}"
api-version: "${apiVersion}"
website: https://github.com/0TickPulse/lccutilities
author: 0TickPulse
libraries:
- org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}
depend:
- MythicMobs